// GENERATED by tools/re/dump_world_graphs.py -- DO NOT EDIT BY HAND.
// Per-world map node graphs + positions, baked from BUMPY.UNPACKED.EXE.
// Graph far-ptr table DS:0x10c8, positions DS:0x10ec (world W at table+W*4).
// Records {state,up,up_d,down,down_d,left,left_d,right,right_d}; 0xff terminates.
// See analysis/specs/screen-flow.md and docs/superpowers/specs/2026-06-27-worlds-2-9-design.md.
#include "game/world_graphs.h"

#include <array>
#include <cstddef>

namespace bumpy {
namespace {

// World 1: 15 nodes. Fields {up, down, left, right, x, y}; [0] = sentinel.
constexpr std::array<MapNode, 16> kWorld1{{
    {0, 0, 0, 0, 0, 0},
    {0, 0, 0, 2, 32, 32},  // node 1
    {0, 9, 1, 0, 112, 32},  // node 2
    {0, 0, 0, 4, 192, 32},  // node 3
    {0, 7, 3, 0, 272, 32},  // node 4
    {0, 8, 0, 0, 32, 80},  // node 5
    {0, 10, 0, 7, 192, 80},  // node 6
    {4, 0, 6, 0, 272, 80},  // node 7
    {5, 12, 0, 9, 32, 128},  // node 8
    {2, 0, 8, 0, 112, 128},  // node 9
    {6, 0, 0, 11, 192, 128},  // node 10
    {0, 15, 10, 0, 272, 128},  // node 11
    {8, 0, 0, 13, 32, 176},  // node 12
    {0, 0, 12, 14, 112, 176},  // node 13
    {0, 0, 13, 15, 192, 176},  // node 14
    {11, 0, 14, 0, 272, 176},  // node 15
}};

// World 2: 15 nodes. Fields {up, down, left, right, x, y}; [0] = sentinel.
constexpr std::array<MapNode, 16> kWorld2{{
    {0, 0, 0, 0, 0, 0},
    {0, 5, 0, 0, 112, 32},  // node 1
    {0, 6, 0, 0, 192, 32},  // node 2
    {0, 7, 0, 0, 272, 32},  // node 3
    {0, 8, 0, 0, 32, 80},  // node 4
    {1, 9, 0, 0, 112, 80},  // node 5
    {2, 10, 0, 0, 192, 80},  // node 6
    {3, 11, 0, 0, 272, 80},  // node 7
    {4, 12, 0, 0, 32, 128},  // node 8
    {5, 13, 0, 0, 112, 128},  // node 9
    {6, 14, 0, 0, 192, 128},  // node 10
    {7, 15, 0, 0, 272, 128},  // node 11
    {8, 0, 0, 13, 32, 176},  // node 12
    {9, 0, 12, 14, 112, 176},  // node 13
    {10, 0, 13, 15, 192, 176},  // node 14
    {11, 0, 14, 0, 272, 176},  // node 15
}};

// World 3: 15 nodes. Fields {up, down, left, right, x, y}; [0] = sentinel.
constexpr std::array<MapNode, 16> kWorld3{{
    {0, 0, 0, 0, 0, 0},
    {0, 5, 0, 2, 32, 32},  // node 1
    {0, 0, 1, 3, 112, 32},  // node 2
    {0, 6, 2, 0, 192, 32},  // node 3
    {0, 7, 0, 0, 272, 32},  // node 4
    {1, 8, 0, 0, 32, 80},  // node 5
    {3, 10, 0, 0, 192, 80},  // node 6
    {4, 11, 0, 0, 272, 80},  // node 7
    {5, 12, 0, 9, 32, 128},  // node 8
    {0, 13, 8, 10, 112, 128},  // node 9
    {6, 14, 9, 11, 192, 128},  // node 10
    {7, 15, 10, 0, 272, 128},  // node 11
    {8, 0, 0, 0, 32, 176},  // node 12
    {9, 0, 0, 0, 112, 176},  // node 13
    {10, 0, 0, 0, 192, 176},  // node 14
    {11, 0, 0, 0, 272, 176},  // node 15
}};

// World 4: 12 nodes. Fields {up, down, left, right, x, y}; [0] = sentinel.
constexpr std::array<MapNode, 13> kWorld4{{
    {0, 0, 0, 0, 0, 0},
    {0, 3, 0, 0, 32, 32},  // node 1
    {0, 9, 0, 0, 272, 32},  // node 2
    {1, 6, 0, 0, 32, 80},  // node 3
    {0, 7, 0, 0, 112, 80},  // node 4
    {0, 8, 0, 0, 192, 80},  // node 5
    {3, 0, 0, 7, 32, 128},  // node 6
    {4, 11, 6, 0, 112, 128},  // node 7
    {5, 12, 0, 9, 192, 128},  // node 8
    {2, 0, 8, 0, 272, 128},  // node 9
    {0, 0, 0, 11, 32, 176},  // node 10
    {7, 0, 10, 12, 112, 176},  // node 11
    {8, 0, 11, 0, 192, 176},  // node 12
}};

// World 5: 12 nodes. Fields {up, down, left, right, x, y}; [0] = sentinel.
constexpr std::array<MapNode, 13> kWorld5{{
    {0, 0, 0, 0, 0, 0},
    {0, 0, 0, 2, 112, 32},  // node 1
    {0, 5, 1, 0, 192, 32},  // node 2
    {0, 0, 0, 4, 32, 80},  // node 3
    {0, 8, 3, 0, 112, 80},  // node 4
    {2, 9, 0, 6, 192, 80},  // node 5
    {0, 10, 5, 0, 272, 80},  // node 6
    {0, 0, 0, 8, 32, 128},  // node 7
    {4, 11, 7, 9, 112, 128},  // node 8
    {5, 0, 8, 0, 192, 128},  // node 9
    {6, 12, 0, 0, 272, 128},  // node 10
    {8, 0, 0, 0, 112, 176},  // node 11
    {10, 0, 0, 0, 272, 176},  // node 12
}};

// World 6: 15 nodes. Fields {up, down, left, right, x, y}; [0] = sentinel.
constexpr std::array<MapNode, 16> kWorld6{{
    {0, 0, 0, 0, 0, 0},
    {0, 5, 0, 0, 32, 32},  // node 1
    {0, 6, 0, 3, 112, 32},  // node 2
    {0, 7, 2, 0, 192, 32},  // node 3
    {0, 8, 0, 0, 272, 32},  // node 4
    {1, 12, 0, 6, 32, 80},  // node 5
    {2, 0, 5, 0, 112, 80},  // node 6
    {3, 10, 0, 8, 192, 80},  // node 7
    {4, 11, 7, 0, 272, 80},  // node 8
    {0, 0, 0, 10, 112, 128},  // node 9
    {7, 14, 9, 0, 192, 128},  // node 10
    {8, 15, 0, 0, 272, 128},  // node 11
    {5, 0, 0, 0, 32, 176},  // node 12
    {0, 0, 0, 14, 112, 176},  // node 13
    {10, 0, 13, 0, 192, 176},  // node 14
    {11, 0, 0, 0, 272, 176},  // node 15
}};

// World 7: 12 nodes. Fields {up, down, left, right, x, y}; [0] = sentinel.
constexpr std::array<MapNode, 13> kWorld7{{
    {0, 0, 0, 0, 0, 0},
    {0, 0, 0, 2, 32, 32},  // node 1
    {0, 6, 1, 3, 112, 32},  // node 2
    {0, 9, 2, 4, 192, 32},  // node 3
    {0, 7, 3, 0, 272, 32},  // node 4
    {0, 8, 0, 0, 32, 80},  // node 5
    {2, 11, 0, 0, 112, 80},  // node 6
    {4, 12, 0, 0, 272, 80},  // node 7
    {5, 10, 0, 0, 32, 128},  // node 8
    {3, 0, 0, 0, 192, 128},  // node 9
    {8, 0, 0, 11, 32, 176},  // node 10
    {6, 0, 10, 12, 112, 176},  // node 11
    {7, 0, 11, 0, 272, 176},  // node 12
}};

// World 8: 15 nodes. Fields {up, down, left, right, x, y}; [0] = sentinel.
constexpr std::array<MapNode, 16> kWorld8{{
    {0, 0, 0, 0, 0, 0},
    {0, 8, 0, 2, 32, 32},  // node 1
    {0, 5, 1, 3, 112, 32},  // node 2
    {0, 6, 2, 4, 192, 32},  // node 3
    {0, 0, 3, 0, 288, 32},  // node 4
    {2, 9, 0, 0, 112, 80},  // node 5
    {3, 10, 0, 7, 192, 80},  // node 6
    {0, 11, 6, 0, 288, 80},  // node 7
    {1, 0, 0, 9, 32, 128},  // node 8
    {5, 13, 8, 10, 112, 128},  // node 9
    {6, 14, 9, 11, 192, 128},  // node 10
    {7, 15, 10, 0, 288, 128},  // node 11
    {0, 0, 0, 13, 32, 176},  // node 12
    {9, 0, 12, 14, 112, 176},  // node 13
    {10, 0, 13, 0, 192, 176},  // node 14
    {11, 0, 0, 0, 288, 176},  // node 15
}};

// World 9: 12 nodes. Fields {up, down, left, right, x, y}; [0] = sentinel.
constexpr std::array<MapNode, 13> kWorld9{{
    {0, 0, 0, 0, 0, 0},
    {0, 7, 0, 0, 32, 32},  // node 1
    {0, 5, 0, 3, 192, 32},  // node 2
    {0, 0, 2, 0, 272, 32},  // node 3
    {0, 8, 0, 5, 112, 80},  // node 4
    {2, 0, 4, 0, 192, 80},  // node 5
    {0, 9, 0, 0, 272, 80},  // node 6
    {1, 10, 0, 0, 32, 128},  // node 7
    {4, 11, 0, 0, 112, 128},  // node 8
    {6, 12, 0, 0, 272, 128},  // node 9
    {7, 0, 0, 11, 32, 176},  // node 10
    {8, 0, 10, 12, 112, 176},  // node 11
    {9, 0, 11, 0, 272, 176},  // node 12
}};

struct WorldTable {
    const MapNode* nodes;
    int count;
};

constexpr std::array<WorldTable, 9> kWorlds{{{kWorld1.data(), 15}, {kWorld2.data(), 15}, {kWorld3.data(), 15}, {kWorld4.data(), 12}, {kWorld5.data(), 12}, {kWorld6.data(), 15}, {kWorld7.data(), 12}, {kWorld8.data(), 15}, {kWorld9.data(), 12}}};

}  // namespace

const MapNode& world_node(int world, int node) {
    return kWorlds[static_cast<std::size_t>(world - 1)].nodes[node];
}

int world_node_count(int world) {
    return kWorlds[static_cast<std::size_t>(world - 1)].count;
}

}  // namespace bumpy
