[sdl]
fullscreen=false
output=surface
waitonerror=false

[dosbox]
machine=vgaonly
memsize=16

[cpu]
core=normal
cputype=386
cycles=fixed 3000

[render]
aspect=false
scaler=none

[mixer]
rate=44100
blocksize=1024
prebuffer=25

[midi]
mididevice=none

[autoexec]
mount c .
c:
