#!/usr/bin/env python3
"""Extract the per-world map node graphs + positions from BUMPY.UNPACKED.EXE and emit
src/game/world_graphs.gen.cpp. Far-pointer tables: graph DS:0x10c8, positions DS:0x10ec,
indexed by world (1-based; world W pointer at table + W*4). Graph records are 9 bytes
{state, up,up_d, down,down_d, left,left_d, right,right_d}, node 1-based (node 0 padding),
0xff state byte terminates. Positions are (x,y) LE words indexed by node-1.
See analysis/specs/screen-flow.md and docs/.../2026-06-27-worlds-2-9-design.md."""
import struct
import pathlib

ROOT = pathlib.Path(__file__).resolve().parents[2]
EXE = ROOT / "analysis/generated/BUMPY.UNPACKED.EXE"
OUT = ROOT / "src/game/world_graphs.gen.cpp"
DS_BASE = 0x11440
GRAPH_TBL = 0x10c8
POS_TBL = 0x10ec
WORLDS = 9

data = EXE.read_bytes()


def u16(off):
    return struct.unpack_from("<H", data, off)[0]


def fo(ds):
    return DS_BASE + ds


def ptr(table, world):
    return u16(fo(table) + world * 4)


def world_nodes(w):
    gbase = fo(ptr(GRAPH_TBL, w))
    pbase = fo(ptr(POS_TBL, w))
    nodes = []
    n = 1
    while data[gbase + n * 9] != 0xFF:
        rec = data[gbase + n * 9 : gbase + n * 9 + 9]
        up, dn, lf, rt = rec[1], rec[3], rec[5], rec[7]
        x = u16(pbase + (n - 1) * 4)
        y = u16(pbase + (n - 1) * 4 + 2)
        if not (0 <= x < 320 and 0 <= y < 200):
            raise SystemExit(f"world {w} node {n}: position out of bounds ({x},{y})")
        nodes.append((up, dn, lf, rt, x, y))
        n += 1
        if n > 64:
            raise SystemExit(f"world {w}: no 0xff terminator within 64 nodes")
    if not nodes:
        raise SystemExit(f"world {w}: empty graph")
    return nodes


worlds = [world_nodes(w) for w in range(1, WORLDS + 1)]

out = []
out.append("// GENERATED by tools/re/dump_world_graphs.py -- DO NOT EDIT BY HAND.")
out.append("// Per-world map node graphs + positions, baked from BUMPY.UNPACKED.EXE.")
out.append("// Graph far-ptr table DS:0x10c8, positions DS:0x10ec (world W at table+W*4).")
out.append("// Records {state,up,up_d,down,down_d,left,left_d,right,right_d}; 0xff terminates.")
out.append("// See analysis/specs/screen-flow.md and docs/superpowers/specs/2026-06-27-worlds-2-9-design.md.")
out.append('#include "game/world_graphs.h"')
out.append("")
out.append("#include <array>")
out.append("#include <cstddef>")
out.append("")
out.append("namespace bumpy {")
out.append("namespace {")
out.append("")
for i, nodes in enumerate(worlds, start=1):
    out.append(f"// World {i}: {len(nodes)} nodes. Fields {{up, down, left, right, x, y}}; [0] = sentinel.")
    out.append(f"constexpr std::array<MapNode, {len(nodes) + 1}> kWorld{i}{{{{")
    out.append("    {0, 0, 0, 0, 0, 0},")
    for idx, (up, dn, lf, rt, x, y) in enumerate(nodes, start=1):
        out.append(f"    {{{up}, {dn}, {lf}, {rt}, {x}, {y}}},  // node {idx}")
    out.append("}};")
    out.append("")
out.append("struct WorldTable {")
out.append("    const MapNode* nodes;")
out.append("    int count;")
out.append("};")
out.append("")
entries = ", ".join(f"{{kWorld{i}.data(), {len(worlds[i - 1])}}}" for i in range(1, WORLDS + 1))
out.append(f"constexpr std::array<WorldTable, {WORLDS}> kWorlds{{{{{entries}}}}};")
out.append("")
out.append("}  // namespace")
out.append("")
out.append("const MapNode& world_node(int world, int node) {")
out.append("    return kWorlds[static_cast<std::size_t>(world - 1)].nodes[node];")
out.append("}")
out.append("")
out.append("int world_node_count(int world) {")
out.append("    return kWorlds[static_cast<std::size_t>(world - 1)].count;")
out.append("}")
out.append("")
out.append("}  // namespace bumpy")
OUT.write_text("\n".join(out) + "\n")
print(f"wrote {OUT} ({WORLDS} worlds, {sum(len(w) for w in worlds)} nodes)")
