#!/usr/bin/env python3
"""Dump BUMPY's PC-speaker "sweep engine" SFX tables to a committed .gen.cpp.

Two kinds of data are emitted:

  * kSfxPresets[0x16] -- the per-sound-id sweep presets from the switch at
    code 1000:6e30 (cases 1..0x15). Each case makes a 9488 (tone) or 9502
    (noise) call whose args are the sweep parameters. These are confirmed
    constants baked from the disassembly (index 0 and 0x13 are unused); the
    literal table lives here so the file stays regenerable and self-documenting.

  * six per-tile speaker maps -- id = table[index], 0 = silent. Copied straight
    out of the data segment of BUMPY.UNPACKED.EXE at file offset 0x11440 + off.

See analysis/specs/game-loop.md and the audio design spec for the trigger sites.

Usage:
    python tools/re/dump_sfx.py [BUMPY.UNPACKED.EXE]          # human-readable dump
    python tools/re/dump_sfx.py --cpp [exe] > src/resources/sfx_tables.gen.cpp
"""
import sys

DATA = 0x11440  # data-segment base -> file offset

# id -> (used, kind, init_divisor, steps, divisor_step, rate_seed, rate_count, rate_step)
# Baked from the 1000:6e30 switch. divisor_step/rate_step are raw u16 (two's complement).
PRESETS = [
    (False, "tone", 0,    0,     0,      0,     0,  0),       # 0x00  unused
    (True,  "tone", 1000, 0x1e,  10,     0x1c2, 1,  1),       # 0x01
    (True,  "tone", 800,  0x28,  0xfff6, 0x1c2, 1,  1),       # 0x02
    (True,  "tone", 440,  400,   0xffff, 499,   4,  0xffff),  # 0x03
    (True,  "tone", 220,  0x5a,  0xffff, 100,   1,  4),       # 0x04
    (True,  "tone", 1000, 0x19,  10,     440,   1,  2),       # 0x05
    (True,  "tone", 1100, 0x14,  10,     440,   2,  5),       # 0x06
    (True,  "tone", 1200, 0x0f,  10,     440,   1,  3),       # 0x07
    (True,  "tone", 220,  0x28,  0xfffb, 100,   1,  5),       # 0x08
    (True,  "tone", 50,   0x1e,  0x14,   0x1c2, 1,  1),       # 0x09
    (True,  "tone", 200,  0x0f,  0x32,   0x15d, 1,  10),      # 0x0a
    (True,  "noise", 0,   0x28,  0x14,   499,   1,  0xfffc),  # 0x0b
    (True,  "tone", 1200, 0x1e,  10,     0x1a4, 1,  2),       # 0x0c
    (True,  "tone", 200,  0x14,  0x32,   0x15d, 2,  0xf),     # 0x0d
    (True,  "tone", 10,   0x32,  4,      200,   10, 0),       # 0x0e
    (True,  "tone", 300,  400,   2,      100,   2,  1),       # 0x0f
    (True,  "tone", 1200, 0x1e,  10,     0x1a4, 1,  2),       # 0x10
    (True,  "noise", 0,   0x28,  0x14,   499,   1,  0xfffc),  # 0x11
    (True,  "noise", 0,   0x50,  0x1e,   499,   2,  0xfffc),  # 0x12
    (False, "tone", 300,  800,   1,      100,   2,  1),       # 0x13  dead case
    (True,  "tone", 10,   0x32,  4,      200,   10, 0),       # 0x14
    (True,  "tone", 600,  0x1e,  10,     0x1c2, 1,  1),       # 0x15
]

# name -> (DS offset, size). Read from the data segment (0x11440 + off).
TILE_TABLES = [
    ("kSfxIdleRest",    0x25de, 0x30),
    ("kSfxRollBump",    0x263e, 0x30),
    ("kSfxFallRoute",   0x269e, 0x30),
    ("kSfxHeldBump",    0x26fe, 0x30),
    ("kSfxLayerBBlock", 0x274e, 0x20),
    ("kSfxPictureBlock", 0x278e, 0x20),
]


def _num(v):
    # Small positive values read clearer as decimal; sweeps stored as u16 negatives as hex.
    return f"0x{v:04x}" if v >= 0x8000 else str(v)


def emit_cpp(f):
    out = []
    out.append("// Auto-generated by tools/re/dump_sfx.py --cpp -- do not edit.")
    out.append("// SFX sweep presets (1000:6e30 switch) + per-tile speaker maps from the")
    out.append("// data segment of BUMPY.UNPACKED.EXE. See tools/re/dump_sfx.py.")
    out.append('#include "resources/sfx_tables.h"')
    out.append("")
    out.append("namespace bumpy {")
    out.append("")
    out.append("const SfxPreset kSfxPresets[0x16] = {")
    for i, (used, kind, init_div, steps, dstep, seed, rcount, rstep) in enumerate(PRESETS):
        fields = "{}, SweepKind::{}, {}, {}, {}, {}, {}, {}".format(
            "true" if used else "false", kind,
            _num(init_div), _num(steps), _num(dstep), _num(seed), _num(rcount), _num(rstep))
        note = " unused" if not used else ""
        out.append(f"    {{{fields}}},  // 0x{i:02x}{note}")
    out.append("};")
    out.append("")
    for name, off, size in TILE_TABLES:
        a = DATA + off
        data = f[a:a + size]
        if len(data) != size:
            raise SystemExit(f"{name}: EXE too small for {size} bytes at 0x{a:x}")
        out.append(f"const std::uint8_t {name}[0x{size:x}] = {{  // DS:0x{off:04x}")
        for row in range(0, size, 16):
            cells = ", ".join(f"0x{b:02x}" for b in data[row:row + 16])
            out.append(f"    {cells},")
        out.append("};")
        out.append("")
    out.append("}  // namespace bumpy")
    out.append("")
    sys.stdout.write("\n".join(out))


def emit_human(f):
    print("=== kSfxPresets (1000:6e30 switch) ===")
    for i, p in enumerate(PRESETS):
        print(f"  0x{i:02x}: {p}")
    print("\n=== per-tile speaker maps (data segment) ===")
    for name, off, size in TILE_TABLES:
        a = DATA + off
        data = f[a:a + size]
        print(f"  {name} DS:0x{off:04x} [{size}]: {[b for b in data]}")


def main():
    args = [a for a in sys.argv[1:] if not a.startswith("--")]
    exe = args[0] if args else r"analysis/generated/BUMPY.UNPACKED.EXE"
    data = open(exe, "rb").read()
    if "--cpp" in sys.argv:
        emit_cpp(data)
    else:
        emit_human(data)


if __name__ == "__main__":
    main()
