#!/usr/bin/env python3
"""Dump BUMPY's player move-script tables from the unpacked binary.

The in-level player ball moves by keyframe scripts, not physics (see
analysis/specs/game-loop.md). `FUN_1000_4263(state)` reads a far-pointer table at
data offset 0x2252 indexed by the player state byte. Each far pointer targets a
6-byte record {count:u8, mirror:u8, script:far}; the script is an array of
`count` triplets {frame:i16, dx:i16, dy:i16} that `FUN_1000_13df` steps one per
frame, translating the ball (dx negated when the mirror/facing flag is set).

Data-segment offsets resolve in BUMPY.UNPACKED.EXE at file offset 0x11440 + off
(established convention; calibrated here against the cloud-jump script at
DS:0x1114). Emits Markdown to stdout.

Usage:
    python tools/re/dump_move_scripts.py [path-to-BUMPY.UNPACKED.EXE] > analysis/specs/move-scripts.md
"""
import sys

DATA = 0x11440  # file offset of data-segment offset 0
TABLE = 0x2252  # move-script far-pointer table
CALIB = 0x1114  # cloud-jump script (calibration)


def main():
    path = sys.argv[1] if len(sys.argv) > 1 else \
        r"analysis/generated/BUMPY.UNPACKED.EXE"
    f = open(path, "rb").read()

    def u16(off):
        a = DATA + off
        return f[a] | (f[a + 1] << 8)

    def s16(off):
        v = u16(off)
        return v - 0x10000 if v >= 0x8000 else v

    def triplets(soff, count):
        return [(u16(soff + i * 6), s16(soff + i * 6 + 2), s16(soff + i * 6 + 4))
                for i in range(count)]

    out = []
    out.append("# Player move-script tables (Stage 3)\n")
    out.append("Auto-generated by `tools/re/dump_move_scripts.py` -- do not hand-edit. "
               "Re-run after re-unpacking the binary.\n")
    out.append("The ball moves by keyframe scripts (no physics). State byte "
               "`DAT_792c` indexes a far-pointer table at `DS:0x2252`; each entry "
               "points to `{count:u8, mirror:u8, script:far}`; the script is "
               "`count` triplets `{frame:i16, dx:i16, dy:i16}` stepped one/frame "
               "by `FUN_1000_13df` (dx negated when facing/mirror is set). "
               "Cell spacing is **40px x 32px**, so a `net` of (+-40,0) or "
               "(0,+-32) is a one-cell move. See "
               "[game-loop.md](game-loop.md) for the state machine.\n")

    # Calibration block proves the decoder + file base.
    cj = triplets(CALIB, 22)
    out.append("## Calibration: cloud-jump script @ DS:0x1114\n")
    out.append("Must match the documented squash/bounce/arc/vanish sequence "
               "(frames 1-7,0 ; bounce dy -3,-2,-2,-1,0,+1,+1,+1 ; arc "
               "0x13,0x16,0x19,0x1c,0x1f ; vanish 0x64).\n")
    out.append("```")
    out.append("frames: " + ",".join(f"{t[0]:#x}" for t in cj))
    out.append("dy:     " + ",".join(f"{t[2]:+d}" for t in cj))
    out.append("```\n")

    out.append("## Move-script table @ DS:0x2252\n")
    for idx in range(0x41):
        rec_off = u16(TABLE + idx * 4)
        if rec_off == 0 or DATA + rec_off + 6 > len(f):
            continue
        count = f[DATA + rec_off]
        mirror = f[DATA + rec_off + 1]
        soff = u16(rec_off + 2)
        if count == 0 or count > 64 or soff == 0 or DATA + soff + count * 6 > len(f):
            out.append(f"### idx {idx:#04x}  (implausible: count={count} script@{soff:#06x}) — skipped\n")
            continue
        tr = triplets(soff, count)
        netx = sum(t[1] for t in tr)
        nety = sum(t[2] for t in tr)
        cell = ""
        if netx % 40 == 0 and nety % 32 == 0:
            cell = f", cell({netx // 40:+d},{nety // 32:+d})"
        out.append(f"### idx {idx:#04x}  count={count} mirror={mirror} "
                   f"script@{soff:#06x}  net=({netx:+d},{nety:+d}){cell}")
        out.append("```")
        out.append("frame " + " ".join(f"{t[0]:>5x}" for t in tr))
        out.append("dx    " + " ".join(f"{t[1]:>+5d}" for t in tr))
        out.append("dy    " + " ".join(f"{t[2]:>+5d}" for t in tr))
        out.append("```\n")

    sys.stdout.write("\n".join(out))


if __name__ == "__main__":
    main()
