#!/usr/bin/env python3
"""Dump BUMPY's player move-script tables from the unpacked binary.

The in-level player ball moves by keyframe scripts, not physics (see
analysis/specs/game-loop.md). `FUN_1000_4263(state)` reads a far-pointer table at
data offset 0x2252 indexed by the player state byte. Each far pointer targets a
6-byte record {count:u8, mirror:u8, script:far}; the script is an array of
`count` triplets {frame:i16, dx:i16, dy:i16} that `FUN_1000_13df` steps one per
frame, translating the ball (dx negated when the mirror/facing flag is set).

Data-segment offsets resolve in BUMPY.UNPACKED.EXE at file offset 0x11440 + off
(established convention; calibrated here against the cloud-jump script at
DS:0x1114). Emits Markdown to stdout, or a baked C++ table with --cpp.

Usage:
    python tools/re/dump_move_scripts.py [path-to-BUMPY.UNPACKED.EXE] > analysis/specs/move-scripts.md
    python tools/re/dump_move_scripts.py --cpp [exe] > src/game/move_scripts.gen.cpp
"""
import sys

DATA = 0x11440  # file offset of data-segment offset 0
TABLE = 0x2252  # move-script far-pointer table
CALIB = 0x1114  # cloud-jump script (calibration)
TABLE_SIZE = 0x41  # state indices 0x00..0x40


def load(path):
    f = open(path, "rb").read()

    def u16(off):
        a = DATA + off
        return f[a] | (f[a + 1] << 8)

    def s16(off):
        v = u16(off)
        return v - 0x10000 if v >= 0x8000 else v

    def triplets(soff, count):
        return [(u16(soff + i * 6), s16(soff + i * 6 + 2), s16(soff + i * 6 + 4))
                for i in range(count)]

    def record(idx):
        """Return (count, mirror, triplets) for state idx, or None if the table
        slot is null / implausible (a scriptless or animation-only state)."""
        rec_off = u16(TABLE + idx * 4)
        if rec_off == 0 or DATA + rec_off + 6 > len(f):
            return None
        count = f[DATA + rec_off]
        mirror = f[DATA + rec_off + 1]
        soff = u16(rec_off + 2)
        if count == 0 or count > 64 or soff == 0 or DATA + soff + count * 6 > len(f):
            return None
        return count, mirror, triplets(soff, count)

    return f, u16, s16, triplets, record


def emit_cpp(record):
    out = []
    out.append("// Auto-generated by tools/re/dump_move_scripts.py --cpp -- do not edit.")
    out.append("// Baked from BUMPY.UNPACKED.EXE move-script table DS:0x2252; see")
    out.append("// analysis/specs/move-scripts.md and analysis/specs/game-loop.md.")
    out.append('#include "game/move_scripts.h"')
    out.append("")
    out.append("namespace bumpy {")
    out.append("namespace {")
    out.append("")
    present = {}
    for idx in range(TABLE_SIZE):
        rec = record(idx)
        if rec is None:
            continue
        count, mirror, tr = rec
        present[idx] = (count, mirror)
        steps = ", ".join(f"{{{fr}, {dx}, {dy}}}" for (fr, dx, dy) in tr)
        out.append(f"constexpr MoveStep kSteps_{idx:02x}[{count}] = {{{steps}}};")
    out.append("")
    out.append(f"constexpr MoveScript kTable[{TABLE_SIZE}] = {{")
    for idx in range(TABLE_SIZE):
        if idx in present:
            count, mirror = present[idx]
            out.append(f"    {{{count}, {mirror}, kSteps_{idx:02x}}},  // 0x{idx:02x}")
        else:
            out.append(f"    {{0, 0, nullptr}},  // 0x{idx:02x} (scriptless / anim-only)")
    out.append("};")
    out.append("")
    out.append("constexpr MoveScript kNull{0, 0, nullptr};")
    out.append("")
    out.append("}  // namespace")
    out.append("")
    out.append("const MoveScript& move_script(std::uint8_t index) {")
    out.append(f"    return index < {TABLE_SIZE} ? kTable[index] : kNull;")
    out.append("}")
    out.append("")
    out.append("}  // namespace bumpy")
    out.append("")
    sys.stdout.write("\n".join(out))


def main():
    cpp = "--cpp" in sys.argv
    args = [a for a in sys.argv[1:] if not a.startswith("--")]
    path = args[0] if args else r"analysis/generated/BUMPY.UNPACKED.EXE"
    f, u16, s16, triplets, record = load(path)

    if cpp:
        emit_cpp(record)
        return

    out = []
    out.append("# Player move-script tables (Stage 3)\n")
    out.append("Auto-generated by `tools/re/dump_move_scripts.py` -- do not hand-edit. "
               "Re-run after re-unpacking the binary.\n")
    out.append("The ball moves by keyframe scripts (no physics). State byte "
               "`DAT_792c` indexes a far-pointer table at `DS:0x2252`; each entry "
               "points to `{count:u8, mirror:u8, script:far}`; the script is "
               "`count` triplets `{frame:i16, dx:i16, dy:i16}` stepped one/frame "
               "by `FUN_1000_13df` (dx negated when facing/mirror is set). "
               "Cell spacing is **40px x 32px**, so a `net` of (+-40,0) or "
               "(0,+-32) is a one-cell move. See "
               "[game-loop.md](game-loop.md) for the state machine.\n")

    # Calibration block proves the decoder + file base.
    cj = triplets(CALIB, 22)
    out.append("## Calibration: cloud-jump script @ DS:0x1114\n")
    out.append("Must match the documented squash/bounce/arc/vanish sequence "
               "(frames 1-7,0 ; bounce dy -3,-2,-2,-1,0,+1,+1,+1 ; arc "
               "0x13,0x16,0x19,0x1c,0x1f ; vanish 0x64).\n")
    out.append("```")
    out.append("frames: " + ",".join(f"{t[0]:#x}" for t in cj))
    out.append("dy:     " + ",".join(f"{t[2]:+d}" for t in cj))
    out.append("```\n")

    out.append("## Move-script table @ DS:0x2252\n")
    for idx in range(0x41):
        rec_off = u16(TABLE + idx * 4)
        if rec_off == 0 or DATA + rec_off + 6 > len(f):
            continue
        count = f[DATA + rec_off]
        mirror = f[DATA + rec_off + 1]
        soff = u16(rec_off + 2)
        if count == 0 or count > 64 or soff == 0 or DATA + soff + count * 6 > len(f):
            out.append(f"### idx {idx:#04x}  (implausible: count={count} script@{soff:#06x}) — skipped\n")
            continue
        tr = triplets(soff, count)
        netx = sum(t[1] for t in tr)
        nety = sum(t[2] for t in tr)
        cell = ""
        if netx % 40 == 0 and nety % 32 == 0:
            cell = f", cell({netx // 40:+d},{nety // 32:+d})"
        out.append(f"### idx {idx:#04x}  count={count} mirror={mirror} "
                   f"script@{soff:#06x}  net=({netx:+d},{nety:+d}){cell}")
        out.append("```")
        out.append("frame " + " ".join(f"{t[0]:>5x}" for t in tr))
        out.append("dx    " + " ".join(f"{t[1]:>+5d}" for t in tr))
        out.append("dy    " + " ".join(f"{t[2]:>+5d}" for t in tr))
        out.append("```\n")

    sys.stdout.write("\n".join(out))


if __name__ == "__main__":
    main()
