#!/usr/bin/env python3
"""Extract the moving-entity (monster) data tables from BUMPY.UNPACKED.EXE:

  * the movement-script descriptor table DS:0x2520 (far ptr -> {count, dir, kf, _}),
    whose keyframes are {frame, dx, dy} word triples (FUN_1000_4bc6 / 4c14);
  * the sprite anim-base table DS:0x2546 (anim index -> a0de base, FUN_1000_2a78);
  * the AI-dispatch tables DS:0x870 (on-arrival) and DS:0x85c (mid-step) for cross-
    checking against the hand-transcribed AI in src/game/level_game.cpp.

The AI *routines* themselves (4dbf/4e44/4ec9/4f4e + leaves) are control flow, not
data, so they are transcribed by hand; only the data tables are baked. Mirrors the
DS->file convention of dump_object_anim.py (file offset = 0x11440 + DS offset).

    python tools/re/dump_entity_ai.py [BUMPY.UNPACKED.EXE]          # human dump
    python tools/re/dump_entity_ai.py --cpp [exe]                   # C++ constexpr
"""
import sys

DATA = 0x11440
DS_SEG = 0x103b
SCRIPT_TABLE = 0x2520
ANIM_BASE_TABLE = 0x2546
AI_ARRIVE = 0x870
AI_MIDSTEP = 0x85c
SCRIPT_COUNT = 10      # ids 0..9; id 0 is a null/idle slot
ANIM_BASE_COUNT = 18   # 0..17 are valid bases; 18+ overlap the next table


def u16(f, off):
    a = DATA + off
    return f[a] | (f[a + 1] << 8)


def s16(v):
    return v - 0x10000 if v > 0x7fff else v


def scripts(f):
    """Return [(id, count, dir, [(frame, dx, dy), ...]), ...] for ids 1..9."""
    out = []
    for i in range(1, SCRIPT_COUNT):
        off = u16(f, SCRIPT_TABLE + i * 4)
        seg = u16(f, SCRIPT_TABLE + i * 4 + 2)
        if seg != DS_SEG:
            break
        count = f[DATA + off]
        direc = f[DATA + off + 1]
        kf = u16(f, off + 2)
        triples = [(u16(f, kf + s * 6), s16(u16(f, kf + s * 6 + 2)), s16(u16(f, kf + s * 6 + 4)))
                   for s in range(count)]
        out.append((i, count, direc, triples))
    return out


def anim_bases(f):
    return [u16(f, ANIM_BASE_TABLE + i * 2) for i in range(ANIM_BASE_COUNT)]


def ai_table(f, base, n=11):
    return [u16(f, base + i * 2) for i in range(n)]


def human(f):
    print("=== DS:0x2520 movement scripts (id: count dir -> {frame,dx,dy}*) ===")
    for i, count, direc, triples in scripts(f):
        print(f"  id {i}: count={count} dir={direc}")
        print(f"        {triples}")
    print("\n=== DS:0x2546 sprite anim bases (index -> a0de) ===")
    for i, b in enumerate(anim_bases(f)):
        print(f"  [{i:2}] 0x{b:04x}")
    print("\n=== DS:0x870 on-arrival AI / DS:0x85c mid-step (FUN_1000_xxxx) ===")
    for i, (a, m) in enumerate(zip(ai_table(f, AI_ARRIVE), ai_table(f, AI_MIDSTEP))):
        print(f"  id {i}: arrive=FUN_1000_{a:04x}  mid=FUN_1000_{m:04x}")


def cpp(f):
    print("// Generated by tools/re/dump_entity_ai.py from BUMPY.UNPACKED.EXE.")
    print("// Moving-entity movement scripts (DS:0x2520) and sprite anim bases (DS:0x2546).")
    print("// Keyframes are {frame, dx, dy}; the entity steps one per active frame (4c14).")
    print("// id 0 is a null slot; ids 1..9 are the real scripts (1=up 2=down 3=left 4=right).")
    flat = []
    spans = {}
    for i, count, direc, triples in scripts(f):
        spans[i] = (len(flat), count, direc)
        flat.extend(triples)
    print(f"constexpr EntityKeyframe kEntityKeyframes[{len(flat)}] = {{")
    for fr, dx, dy in flat:
        print(f"    {{{fr}, {dx}, {dy}}},")
    print("};")
    print(f"constexpr EntityScript kEntityScripts[{SCRIPT_COUNT}] = {{")
    print("    {0, 0, 0},  // id 0: null/idle")
    for i in range(1, SCRIPT_COUNT):
        kf, count, direc = spans[i]
        print(f"    {{{kf}, {count}, {direc}}},  // id {i}")
    print("};")
    bases = anim_bases(f)
    print(f"constexpr std::uint16_t kEntityAnimBase[{len(bases)}] = {{")
    print("    " + ", ".join(f"0x{b:04x}" for b in bases))
    print("};")


def main():
    argv = [a for a in sys.argv[1:] if a != "--cpp"]
    path = argv[0] if argv else "analysis/generated/BUMPY.UNPACKED.EXE"
    f = open(path, "rb").read()
    (cpp if "--cpp" in sys.argv else human)(f)


if __name__ == "__main__":
    main()
